[package]
name = "vault_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "vault_core"
crate-type = ["cdylib"]

[dependencies]
# JSON serialization / deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

#for chacha20's dependency
base64ct = {version = "1.7.0"}

# Argon2 KDF
argon2 = "0.4"

# XChaCha20Poly1305 AEAD cipher
chacha20poly1305 = "0.8"
chacha20 = "0.8"

# Base64 encoding
base64 = "0.21"


# Random number generation
rand = "0.8"
rand_core = "0.6"

# For reading passwords without echo in terminal
rpassword = "7.0"

# For better error handling
anyhow = "1.0"

# For communication between frontend python and backend rust
pyo3 = {version = "0.21", features = ["extension-module"]}